tests: Implement a way to test nixvim
pta2002/nixvim pull request #199
Opened 2023-02-24 21:27 UTC by traxys

The tests can be executed using `nix flake check`, they check that modules can be built, and they execute in neovim without any errors.

This commit only implements tests for tokyonight-nvim upstream defaults

2023-02-25 13:21 UTC, pta2002 commented
I'd like to check on this one myself before merging, so give me a moment before approving @GaetanLepage :)

Seems like a great idea just skimming though

2023-02-25 13:23 UTC, pta2002 requested changes
This is great and I like the way you approach it. However, could you move each check to a separate file? And then just load all files automatically, like it's done for the module loading in flake.nix

2023-02-25 14:48 UTC, traxys commented
Sure!
By automatically you mean creating a file with lots of `imports = [./<...> ./<....> ./<....>]`

2023-02-26 12:38 UTC, traxys commented
@pta2002 is this more what you had in mind  ?

2023-02-26 13:13 UTC, pta2002 commented
I meant more in the sense of listing the directory automatically, like it's done in flake.nix to load the modules, that way there's no need to list everything manually

2023-02-26 13:16 UTC, traxys commented
I feel like this would be enough automation, you just have list a new file in attrset, I fear that too much automation would make things brittle

2023-02-26 21:07 UTC, traxys commented
@pta2002 Could you point me to the exact lines you mean ? I don't really understand

2023-02-27 10:34 UTC, pta2002 commented
Yes, here you go:

```nix
      nixvimModules = map (f: ./modules + "/${f}") (attrNames (builtins.readDir ./modules));
```

2023-02-28 19:24 UTC, traxys commented
This should be more automatic!

2023-02-28 22:21 UTC, pta2002 approved these changes

2023-02-28 22:21 UTC, pta2002 commented
Awesome!

2023-02-28 22:22 UTC, pta2002 commented
@GaetanLepage requesting your review since it's a big change

2023-02-28 22:22 UTC, GaetanLepage approved these changes
Seems good now !

2023-02-28 23:39 UTC, merged