Added flake template
pta2002/nixvim pull request #219
Opened 2023-03-01 22:35 UTC by Alexnortung

I have added a flake template, which I think can be beneficial for new Nixvim users and users who do not yet use standalone.

I have also exposed some of the lib in the flake. This allows the template to use the check function defined in lib.
Another benefit of exposing lib is that it might be more intuitive to use the helpers this way, compared to the current one where you need to access `config.nixvim.helpers`, instead you can use `inputs.nixvim.lib.helpers`.

2023-03-02 09:11 UTC, GaetanLepage commented
Thanks for this contribution.
I have not tested it, but looking at the code, the changes look good to me !

2023-03-02 12:57 UTC, GaetanLepage approved these changes

2023-03-02 13:00 UTC, pta2002 requested changes

2023-03-02 13:00 UTC, pta2002 commented on templates/simple/flake.nix
> +      pkgs = nixpkgs.legacyPackages.${system};
Can this be changed to use `import nixpkgs { inherit system; }` instead?

2023-03-03 09:18 UTC, pta2002 approved these changes
that's it, great! thanks :)

2023-03-03 09:18 UTC, merged