lualine: add winbar and inactive sections configs
pta2002/nixvim pull request #302
Opened 2023-03-30 00:45 UTC by andrevmatos

Simple PR to expand lualine config to allow winbar and inactive sections and winbar components config.

2023-03-30 07:58 UTC, GaetanLepage requested changes
Hello, 
Here are a few minor requested changes.

2023-03-30 07:58 UTC, GaetanLepage commented on plugins/statuslines/lualine.nix
> +      name;
```suggestion
    mkEmptySectionOption = name:
      helpers.mkCompositeOption name {
        lualine_a = mkComponentOptions "";
        lualine_b = mkComponentOptions "";
        lualine_c = mkComponentOptions "";
        lualine_x = mkComponentOptions "";
        lualine_y = mkComponentOptions "";
        lualine_z = mkComponentOptions "";
      };
```

2023-03-30 07:58 UTC, GaetanLepage commented on plugins/statuslines/lualine.nix
> +      inactive_sections =
```suggestion
      inactiveSections =
```

2023-03-30 07:58 UTC, GaetanLepage commented on plugins/statuslines/lualine.nix
>          helpers.mkNullOrOption
```suggestion
        helpers.mkCompositeOption "Inactive Sections configuration" {
          lualine_c = mkComponentOptions "filename";
          lualine_x = mkComponentOptions "location";
        };
```

2023-03-30 07:58 UTC, GaetanLepage commented on plugins/statuslines/lualine.nix
> +      inactive_winbar = mkEmptySectionOption "Inactive Winbar configuration";
```suggestion
      inactiveWinbar = mkEmptySectionOption "Inactive Winbar configuration";
```

2023-03-30 07:58 UTC, GaetanLepage commented on plugins/statuslines/lualine.nix
> +      inactive_sections = mapNullable processSections cfg.inactive_sections;
```suggestion
      inactive_sections = mapNullable processSections cfg.inactiveSections;
```

2023-03-30 07:58 UTC, GaetanLepage commented on plugins/statuslines/lualine.nix
> +      inactive_winbar = mapNullable processSections cfg.inactive_winbar;
```suggestion
      inactive_winbar = mapNullable processSections cfg.inactiveWinbar;
```

2023-03-30 14:06 UTC, GaetanLepage commented
Thanks for the corrections.
One last thing: could you add a test please ?

1. create `tests/test-sources/plugins/statuslines/lualine.nix`
2. Create two (or three) configurations:
  - An `empty` one, where you just enable the plugin
  - A `defaults` one, where you set all the options to the plugin's defaults.
  (- An `example` one where you provide a sensible config)

You can have a look to other test files to see how it works.

2023-04-01 00:28 UTC, andrevmatos commented
@GaetanLepage done; I'm not too much into Nix testing, but I hope this should be enough. Thanks

2023-04-01 08:05 UTC, GaetanLepage commented
> @GaetanLepage done; I'm not too much into Nix testing, but I hope this should be enough. Thanks

Perfect, thanks !

2023-04-01 08:41 UTC, GaetanLepage approved these changes
Everything looks good now

2023-04-01 08:42 UTC, merged