Added test for template and fixed check export for lib
pta2002/nixvim pull request #361
Opened 2023-05-13 22:04 UTC by Alexnortung

lib/default.nix was missing the check file, which is now moved to test-derivation.nix.
Here it was important to export both functions as the config for mkTestDerivation does not support imports from a configuration.

the check workflow also got a test for the template so we can keep it up to date, when making some breaking changes.

2023-05-13 22:21 UTC, traxys requested changes
Could you add a README in the templates/_wrapper directory to explain that this directory stores tests for the templates ?

2023-05-13 23:07 UTC, Alexnortung commented
Sure! I am not sure what you mean by the same command in the pre-commit hook? Do you mean I should add the check command to the pre-commit hooks?

2023-05-14 08:47 UTC, traxys commented
Sorry I meant the command in the action workflow

2023-05-14 21:49 UTC, GaetanLepage commented on templates/_wrapper/simple/flake.nix
> +    # };
Shouldn't this be removed ?
```suggestion
```

2023-05-15 09:04 UTC, traxys approved these changes

2023-05-15 09:04 UTC, merged